## RSA - The Project

<hr />

# Table of Contents

### 1. Introduction

### 2. RSA Code Package
###### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2.1 Basic tool set
###### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2.2 First tool set
###### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2.3 Second tool set

### 3. RSA More Code

###### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Encode
###### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Decode

### 4. Demo of encoding and decoding a message that highlights how the code works and the steps involved.

### 5. Results of exchanging codes with others.  

### 6. Narrative

### 7. Why FME?

### 8. How to break codes

### 9. Code breaking complete examples

### 10.Custom code feature / Advanced options







### 1. Introduction to the RSA Package and Project.

   In the following sections, one of the most common public-key encryption schemes, called RSA, will be explored and also built from the ground up. Every single day we utilize numerous these concepts to esnure security and saftey of our information online. It is thanks to RSA that our transactions online are not public knowledge. Even more importatnly RSA is key in garuanteeting the saftey of our passwords, bank account information, electronic payment transactions, and so much more. During this project I explored critical number theory concepts that play an integral role in the modern RSA public-key encryption scheme, namely, prime factorization, modular arithmetic and greatest common divisors.
   
   In the following sections I first implemented a basic tool set that would process messages before or after they went through the RSA algorithm. Then, using the concepts from the book and lectures, I implemented a function to take care of fast modular exponentiation and the basic and extended eucleidan algorithms. Once all these helper functions were created, functions to find public and privated keys were created as well as those used to encode and decode messages. In the rest of this project, these functions are then utilized to exchange messages and more of my journey is outlined. In the end, I then take a crack at breaking codes and analyze the security of RSA. Thank you for taking the time to read through this project and my findings.
    

### 2.1
#### Basic tool set

These are functions that are needed to pre-process the messages before the messages are encoded and decoded by the RSA algorithm. 


In [13]:
def Convert_Text(_string):
    """
    Define this function such that it takes in a simple 
    string such as "hello" and outputs the corresponding
    standard list of integers (ascii) for each letter in the word hello.
    For example:
    _string = hello
    integer_list = [104, 101, 108, 108, 111]
    
    You may use "ord()"
    """
    integer_list = [] # declare a list to hold each integer
    
    for i in _string: # loop through each character in the string
        integer_list.append(ord(i)) #get the Unicode code for the charcter and add it to the list
    
    return integer_list # return the list of integers


In [14]:
def Convert_Num(_list):
    """
    Do the opposite of what you did in the Convert_Text
    function defined above.
    
    Define this function such that it takes in a list of integers
    and outputs the corresponding string (ascii).
    
    For example:
    _list = [104, 101, 108, 108, 111]
    _string = hello
    
    I used built-in function chr for this implementation.
    https://docs.python.org/3/library/functions.html#chr
    """
    _string = '' #declare variable to hold the string
    
    for i in _list: # loop through each number in the list
        _string += chr(i) # use built-in function chr to convert Unicode in to ASCII
        
    return _string # return the string


In [15]:
def Convert_Binary_String(_int):
    """
    Here, you need to define a function that converts an integer to
    a string of its binary expansion.
    
    For example:
    _int = 345
    bits = 101011001
    
    I used built-in function bin for this implementation.
    https://docs.python.org/3/library/functions.html#bin
    """
    bits = bin(_int)[2:] #use built-in function bin to convert from int to binary and ignore the first two charcters which are 0b
    
    return bits


### 2.2 
#### First tool set.



In [16]:
def FME(b, n, m):
   
    reversedBinaryString = [] # declare empty array to hold the reversed string
    while True: # loop untill break is called
        reversedBinaryString.append(( n % 2)) # find the remainder and create a string in big endian format
        n = int((n - (n % 2)) / 2)  # divided the quotient by 2
        if ( n <= 0):   # loop untill there is no quotient remaining 
            break       # exit loop when the there is no remainder

    binaryStringLength = len(reversedBinaryString) #intailze a variable with the length of the array
    result = 1 #declare a variable to hold the result
    square = b #intialze the squre value with the user input
    i = 0   #delcare counter for array postion

    while i < binaryStringLength: #loop through the whole binary string
        if(reversedBinaryString[i] == 1): #check if the current bit postion is even
            result = (result * square) % m #mulitply the result by the base and then take mod m

        square = (square * square) % m #sqare the square and then take mod m every time

        i += 1 #increment the postion counter
    return result #print the result

In [17]:
def Euclidean_Alg(a, b):
    """
    1. Calculate the Greatest Common Divisor of a and b.
    
    2. This version should have only postive inputs and outputs.
    
    3. 
    
    The function must return a single integer 'x' which is
    the gcd of a and b.
    
    """
    
    if(a < 0 or b < 0): # check to ensure that the inputs are postive
        print("All inputs have to be positive, please try again") # print error message
        return # exit the function
    
    if(a < b): # check to ensure that a is larger than b
        temp = a # decalre temp variable to hold value of a
        a = b # assign value of b to a
        b = temp # assign old value of a to b
    
    while(b > 0): # loop untill b is no longer greater than 0
        k = a % b # declare k to hold the remainder of a / b
        a = b # assign a to b
        b = k # assign b to the remainder
        
    return a # return the gcd of the orignal values of a and b

In [18]:
def extendedEuclideanAlg(m, n):
    """
    This is a helper function used in Find_Private_Key_d() 

    This function returns m, s1, and t1 which is 
    the gcd of the two original inputs and the coresponding Bezout coefficents
    """
    m0, n0 = m, n   # initialize constants m0 and n0 to store intial values of m and n
    s1, t1 = 1, 0   # initialize Bezout coefficients s1 and t1 with 1 and 0
    s2, t2 = 0, 1   # initialize Bezout coefficients s2 and t2 with 0 and 1
        
    while (n > 0):
        k = m % n   # compute the reminder by taking m mod n
        q = m // n  # compute the quotient and round down to nearest whole number 
        
        m = n   # set m to the current value of n
        n = k   # set n equal to the remainder
            
        s1_temp, t1_temp = s2, t2  # declare temp variables to hold the old values of s2 and t2
        s2_temp, t2_temp = s1-q*s2, t1-q*t2 # declare temp variables to hold updated Bezout coefficients
            
        s1, t1 = s1_temp, t1_temp   # update the Bezout coefficients for s1 and t1
        s2, t2 = s2_temp, t2_temp   # update the Bezout coefficients for s2 and t2
    
    return m, s1, t1 #print out the gcd and the Bezout coefficients

### 2.3
#### Second tool set

Here is the implemtnation of the core of the RSA cryptosystem. The functions below will generate the public and private key pairs which will then be used to create a ciphertext using the public key and then decode the same using the pirvate key.



In [19]:
import random as random

def Find_Public_Key_e(p, q):
    """
    This function takes 2 primes p and q.
    
    The function returns 2 elements as follows:
    public key: n
    public key: e    
    """
    
    n = p * q # find the product of p and q
    
    if(n < 150):  # p*q should be larger thatn 150 to avoid issues with ASCII
        print("Product is less than 150 please select larger prime numbers") # print a error message 
        return  # exit the function
        
    while True: #loop until the loop is exited
        e = random.randrange(10,10000)  # randomly pick a value for e
        #check if the value of e is relatively prime to (p-1) * (p-1)
        if (Euclidean_Alg(e, (p-1) * (q-1)) == 1 and e != p and e != q): 
            break   # if e is realatively prime exit the loop
        
    return n, e #return public key

In [20]:
def Find_Private_Key_d(e, p, q):
    """
    This method finds the decryption exponent d such that
    d is the modular inverse of e. 
    
    This will use the Extended Euclidean Algorithm
    
    This function returns the following:
    d: the decryption component.    
    """
    phi = (p-1) * (q-1) # Find Euler's totient
    
    m, s, t = extendedEuclideanAlg(e, phi) # Use the Extended Euclidean Algorithm to claculate the gcd and bezout coefficients
    
    d = s # Assign the bezout coefficent that is the inverse of e
    
    while(d < 0): # ensure that d is not negative
        d += phi  # if d is negative find a postive value that is congruent under the modulus to d
        
    return d # return the decryption exponent

### 3.
#### Putting things all together.

1. In this part, I have defined two functions `Encode` and `Decode` which will use the public and private keys that were calculated using the above 2 functions in the second toolset.
2. Using the public key, the `Encode` function will encode a message and generate the corresponding cipher_text.
3. Using the private key, the `Decode` function will decode a ciper_text and recover the original message.



In [21]:
def Encode(n, e, message):
    """
    Here, the message will be a string of characters.
    Useing the function Convert_Text from 
    the basic tool set we get a list of numbers.
    
    Each of those numbers are encoded using n and e and
    the encoded cipher_text is returned.
    """
    cipher_text = [] #decalre an array to hold the encoded message
    
    integers_list = Convert_Text(message) #convert the string of characters into ASCII
    
    for i in integers_list: # loop through each element in the list
        cipher_text.append(FME(i, e, n)) # use FME to encode each number using e and n and then add it to the encrypted list
    
    return cipher_text # return the encoded message

In [22]:
def Decode(n, d, cipher_text):
    """
    Here, the cipher_text will be a list of integers.
    First, each of those integers is decrypted using 
    n and d.
    
    The fnction Convert_Num, that converts the integers to a string, 
    from the basic toolset is used to recover the original message as a string. 
    
    """
    message = '' # declare message to hold the decoded character string
    decoded = [] # declare decoded to hold the decoded ASCII list
    
    for i in cipher_text: # loop through each element in the encoded array
        decoded.append(FME(i, d, n)) # use FME to decode each number using d and n and then add it to the decoded list
        
    message = Convert_Num(decoded) # convert the ASCII into a string of characters
    
    return message # return the decoded message

### 4. Demo 
This is a step by step guide to using my code with a specific examples that can be followed using the functions created above. 
Basically this is a test that demonstates that the code works.


* Generate Keys - describing your method in the text block

* Encode a message.

* Decode a message from Piazza

* Add new blocks by using the A and B keys - select text or code above.


#### Generating Keys
Now that all the code above has been developed it is time for us to begin the RSA process, the first step being that I have to create my own Public and Private Keys. In order to do this we must first find 2 prime number's p and q. This can easily be done by looking up prime numbers and then picking two of them. However, if the product of these two are less than 150, the user will get an error message and be asked to choose another two prime numbers. For this demo I chose p to be 43 and q to be 97. Each time this is run a new value of e will be returned as I am utlizing the random funciton in python.

In [23]:
(n,e) = Find_Public_Key_e(43,97)
print (n,e)

4171 6781


Now that we have our public key (4171, 1909) that we can send out we must next cauclute d and get the private key. This function utilzies the extended eculidean algoritim to find the inverse of e modulo (43-1) * (97-1).

In [24]:
#first run I got 4171, 1909 for the public key

d = Find_Private_Key_d(1909,43,97)
print(d)

2845


Now we also have found our private key (4171, 2845) and can move on to encoding a message and then decoding a message. 

#### Encoding a Message
Now with our public key (4171, 1909) we can encoude a message, utilizing FME, as seen below.

In [25]:
# Public key n,e = (4171, 1909)

message = "Test run to ensure that encyrption and decryption has a properly working implementation"
encode_q = Encode(4171, 1909, message)
print(encode_q)

[2978, 2421, 1754, 3512, 3467, 2739, 1485, 3521, 3467, 3512, 1434, 3467, 2421, 3521, 1754, 1485, 2739, 2421, 3467, 3512, 157, 2037, 3512, 3467, 2421, 3521, 1605, 170, 2739, 2512, 3512, 564, 1434, 3521, 3467, 2037, 3521, 2976, 3467, 2976, 2421, 1605, 2739, 170, 2512, 3512, 564, 1434, 3521, 3467, 157, 2037, 1754, 3467, 2037, 3467, 2512, 2739, 1434, 2512, 2421, 2739, 727, 170, 3467, 992, 1434, 2739, 3143, 564, 3521, 3207, 3467, 564, 1773, 2512, 727, 2421, 1773, 2421, 3521, 3512, 2037, 3512, 564, 1434, 3521]


To test that this message has been properly encoded let us try and decode it using our private key. Just like when encrypting a message, decryption also utilzies FME.

In [26]:
# Private key n,d = (4171, 2845)

d = [2978, 2421, 1754, 3512, 3467, 2739, 1485, 3521, 3467, 3512, 1434, 3467, 2421, 3521, 1754, 1485, 2739, 2421, 3467, 3512, 157, 2037, 3512, 3467, 2421, 3521, 1605, 170, 2739, 2512, 3512, 564, 1434, 3521, 3467, 2037, 3521, 2976, 3467, 2976, 2421, 1605, 2739, 170, 2512, 3512, 564, 1434, 3521, 3467, 157, 2037, 1754, 3467, 2037, 3467, 2512, 2739, 1434, 2512, 2421, 2739, 727, 170, 3467, 992, 1434, 2739, 3143, 564, 3521, 3207, 3467, 564, 1773, 2512, 727, 2421, 1773, 2421, 3521, 3512, 2037, 3512, 564, 1434, 3521]
d = Decode(4171, 2845, d)
print(d)

Test run to ensure that encyrption and decryption has a properly working implementation


#### Decode a message from someone else
Now that we have seen that creating our own public and private keys allows use to encrypt and decyrpt our own message lets try decoding one of the messages that was given to us. To do this I used the private key that was provided and my Decode funciton to find the contents of the orignal message.

In [27]:
# Public key n,e = (5251,3)
# Private key n,d = (5251, 3403)

encoded_message = [2128, 1150, 4250, 1349, 1262, 3336, 2371, 2497, 519, 1262, 1263, 1105, 3336, 1349, 1262, 2310, 1105, 3336, 4115, 762, 2405, 1263, 1105, 3336, 1262, 1349, 1150, 1105, 1262, 506, 1105, 1105, 4723, 2405, 2497, 519, 1262, 1974, 2371, 58, 1262, 519, 1105, 1349, 1262, 4839, 1150, 1105, 2497, 1262, 1974, 2371, 58, 762, 1262, 13, 4679, 1573, 1262, 4115, 2371, 2310, 1105, 1262, 2405, 3336, 1262, 4839, 2371, 762, 1560, 2405, 2497, 519, 3250]
orignial_message = Decode(5251, 3403, encoded_message)
print(orignial_message)

What song best describes the feeling you get when your RSA code is working?


Now that I had a message, it was time to come up with an answer. As I choose Levitating (feat. DaBaby) by Dua Lipa, I then used the public key to encrypt this message and send it back.

In [29]:
feeling = "Levitating (feat. DaBaby) by Dua Lipa"
encode_feeling = Encode(5251, 3, feeling)
print(encode_feeling)

[3143, 1105, 4720, 2405, 1349, 4250, 1349, 2405, 2497, 519, 1262, 988, 506, 1105, 4250, 1349, 2818, 1262, 4623, 4250, 3942, 4250, 1263, 1974, 658, 1262, 1263, 1974, 1262, 4623, 58, 4250, 1262, 3143, 2405, 2911, 4250]


### 5.

#### Response to Song Prompt

In [30]:
# Public key n,e = (5251,3)
# Private key n,d = (5251, 3403)
message = [2128, 1150, 4250, 1349, 1262, 3336, 2371, 2497, 519, 1262, 1263, 1105, 3336, 1349, 1262, 2310, 1105, 3336, 4115, 762, 2405, 1263, 1105, 3336, 1262, 1349, 1150, 1105, 1262, 506, 1105, 1105, 4723, 2405, 2497, 519, 1262, 1974, 2371, 58, 1262, 519, 1105, 1349, 1262, 4839, 1150, 1105, 2497, 1262, 1974, 2371, 58, 762, 1262, 13, 4679, 1573, 1262, 4115, 2371, 2310, 1105, 1262, 2405, 3336, 1262, 4839, 2371, 762, 1560, 2405, 2497, 519, 3250]
message_decode = Decode(5251, 3403, message)
print(message_decode)

What song best describes the feeling you get when your RSA code is working?


In [31]:
song_response = "Levitating (feat. DaBaby) by Dua Lipa"
encode_song = Encode(5251, 3, song_response)
print(encode_song)

[3143, 1105, 4720, 2405, 1349, 4250, 1349, 2405, 2497, 519, 1262, 988, 506, 1105, 4250, 1349, 2818, 1262, 4623, 4250, 3942, 4250, 1263, 1974, 658, 1262, 1263, 1974, 1262, 4623, 58, 4250, 1262, 3143, 2405, 2911, 4250]


In [32]:
encrypted_song = [3143, 1105, 4720, 2405, 1349, 4250, 1349, 2405, 2497, 519, 1262, 988, 506, 1105, 4250, 1349, 2818, 1262, 4623, 4250, 3942, 4250, 1263, 1974, 658, 1262, 1263, 1974, 1262, 4623, 58, 4250, 1262, 3143, 2405, 2911, 4250]
decoded_song = Decode(5251, 3403, encrypted_song)
print(decoded_song)

Levitating (feat. DaBaby) by Dua Lipa


#### My Own Question and a Response

In [33]:
#Public key n,e = (4171, 9827)
#Private key n,d = (4171, 3275)

my_question = "If you could have one superpower what would it be and how would you use it?"
encoded_question = Encode(4171, 9827, my_question)
print(encoded_question)

[1839, 1368, 2103, 489, 1708, 240, 2103, 3966, 1708, 240, 2, 169, 2103, 1044, 1552, 1157, 3807, 2103, 1708, 1041, 3807, 2103, 691, 240, 2757, 3807, 1224, 2757, 1708, 3470, 3807, 1224, 2103, 3470, 1044, 1552, 2785, 2103, 3470, 1708, 240, 2, 169, 2103, 2743, 2785, 2103, 2426, 3807, 2103, 1552, 1041, 169, 2103, 1044, 1708, 3470, 2103, 3470, 1708, 240, 2, 169, 2103, 489, 1708, 240, 2103, 240, 691, 3807, 2103, 2743, 2785, 1533]


In [34]:
prof_repsonse = [8, 2, 489, 2743, 1041, 81, 2179, 2103, 1292, 2426, 691, 1708, 2, 240, 2785, 3807, 2, 489, 2179, 2103, 1839, 2103, 3470, 1708, 240, 2, 169, 2103, 2565, 240, 691, 2785, 2103, 1368, 2, 489, 2103, 1552, 1224, 1708, 240, 1041, 169, 2103, 1552, 2, 2, 2103, 2785, 1044, 3807, 2103, 2785, 2743, 273, 3807, 2179, 2103, 1292, 1041, 169, 2103, 273, 1552, 489, 2426, 3807, 2103, 1224, 3807, 691, 3966, 240, 3807, 2103, 2757, 3807, 1708, 2757, 2, 3807, 2103, 3807, 1157, 3807, 1224, 489, 2103, 1041, 1708, 3470, 2103, 1552, 1041, 169, 2103, 2785, 1044, 3807, 1041, 2179]
decode_prof_response = Decode(4171, 3275, prof_repsonse)
print(decode_prof_response)

Flying. Absolutely. I would just fly around all the time. And maybe rescue people every now and then.


#### Response to Another Question

In [35]:
# Public Key n, e = (161, 13)
# Private Key n, d = (161, 61)
student_question = [94, 76, 96, 3, 156, 81, 128, 76, 96, 81, 114, 90, 116, 6, 150, 114, 81, 150, 90, 116, 81, 76, 96, 116, 115, 77, 156, 150, 81, 76, 114, 81, 150, 90, 116, 81, 77, 117, 56]
student_question_decode = Decode(161, 61, student_question)
print(student_question_decode)

Would you rather eat outside or eat in?


In [36]:
eating_response = "Even though eating in requries more effort I often enjoy the process and find that I also enjoy the food more as a result of my hard work."
encode_eating_response = Encode(161, 13, eating_response)
print(encode_eating_response)

[69, 55, 150, 117, 81, 116, 6, 76, 96, 40, 6, 81, 150, 90, 116, 77, 117, 40, 81, 77, 117, 81, 114, 150, 134, 96, 114, 77, 150, 115, 81, 102, 76, 114, 150, 81, 150, 130, 130, 76, 114, 116, 81, 108, 81, 76, 130, 116, 150, 117, 81, 150, 117, 57, 76, 128, 81, 116, 6, 150, 81, 14, 114, 76, 43, 150, 115, 115, 81, 90, 117, 156, 81, 130, 77, 117, 156, 81, 116, 6, 90, 116, 81, 108, 81, 90, 3, 115, 76, 81, 150, 117, 57, 76, 128, 81, 116, 6, 150, 81, 130, 76, 76, 156, 81, 102, 76, 114, 150, 81, 90, 115, 81, 90, 81, 114, 150, 115, 96, 3, 116, 81, 76, 130, 81, 102, 128, 81, 6, 90, 114, 156, 81, 154, 76, 114, 51, 46]


In [37]:
eating_response = [69, 55, 150, 117, 81, 116, 6, 76, 96, 40, 6, 81, 150, 90, 116, 77, 117, 40, 81, 77, 117, 81, 114, 150, 134, 96, 114, 77, 150, 115, 81, 102, 76, 114, 150, 81, 150, 130, 130, 76, 114, 116, 81, 108, 81, 76, 130, 116, 150, 117, 81, 150, 117, 57, 76, 128, 81, 116, 6, 150, 81, 14, 114, 76, 43, 150, 115, 115, 81, 90, 117, 156, 81, 130, 77, 117, 156, 81, 116, 6, 90, 116, 81, 108, 81, 90, 3, 115, 76, 81, 150, 117, 57, 76, 128, 81, 116, 6, 150, 81, 130, 76, 76, 156, 81, 102, 76, 114, 150, 81, 90, 115, 81, 90, 81, 114, 150, 115, 96, 3, 116, 81, 76, 130, 81, 102, 128, 81, 6, 90, 114, 156, 81, 154, 76, 114, 51, 46]
decode_eating_response = Decode(161, 61, eating_response)
print(decode_eating_response)

Even though eating in requries more effort I often enjoy the process and find that I also enjoy the food more as a result of my hard work.


### 6. Narrative 


#### Code Exchange and Mistakes
As I responded to the question posted by Professor Stade’s in the thread to exchange codes and keys, I felt like I was levitating once I got it all working. When initially exchanging codes with others, I found that I was able to respond to Professor Stade's message and decrypt it with no issue. From here I was also able to send a response and encrypt it without any issues so I thought to myself that it would just be smooth sailing from here on out. However, after I procced to send my own message, I joined weekly office hours to just discuss my progress and thoughts with Professor Stade, it was at this point were she pointed out that she was unable to decrypt my message. When I went to decrypt my own message, I obtained the following results:
ੱુݣƯག૆ݣਸག૆αʩݣݫƄࡥ࡟ݣགŞ࡟ݣ౵૆ೋ࡟௉ೋགߟ࡟௉ݣߟݫƄഡݣߟག૆αʩݣ཮ഡݣְ࡟ݣƄŞʩݣݫགߟݣߟག૆αʩݣƯག૆ݣ૆౵࡟ݣ཮ഡ઺

I was baffled as I was sure my implementation for each function followed what we learned in lectures as well as what the book for this class had told me. As I went back to test each and every function one by once again, I saw that everything worked as expected. Confused, I took a step away to clear my head and come back to this issue with a fresh pair of eyes. When I came back, I saw the silly mistake that I had made. In my excitement, I went about creating my own keys too fast and in the process I mixed up e, q, and p for my Find_Private_Key_d() function. This caused me to be unable to properly decode my message as the private key did not return the proper value for d and it was not the inverse of e modulo (p-1)*(q-1). By fixing this careless mistake, I was able to get the proper message that I had tried to send when decoding my encoded list.
#### Process, Hurdles, and Resources
When I first started this process, I read over each of the descriptions of the functions on week 1. At this point I admitted to myself that I didn’t have enough of the knowledge to start the implementation, so I spent the first week and a half reading the book and watching each of the lecture videos. In the lectures Sriram provided algorithms for many of the toolsets in part one so after watching these videos I coded the corresponding functions. Doing this I was able to complete the basic toolset, and at this point I turned to section 4.6 to finalize the encode and decode functions. This was the part that took me the longest as the book gave the formulas, but before I implemented these, I wanted to understand how the math behind it worked.
While the number theory concepts and math behind this project did not cause me too much trouble, the actual python implementation took me the most time as figuring out how to turn these mathematical formulas into steps in pythons proved to take some time for me as this is my first exposure to python. Thus, I must credit Sriram for help on a lot of this project as he essentially provided a lot of the code that I used. However, outside of this the Piazza threads helped get my brain turning when I was faced with a wall. 
While all these resources did help, I must admit that the Best RSA Graphic Ever deserves its name. This resource was my first go to whenever doing anything on this project as it gave me the entire view of what I needed to get done and how it all fit together. For me this concept of zooming out then zooming in again proved to be most helpful when looking at the project and putting it all together. Even when I started, looking at the Best RSA Graphic Ever before coding allowed me to look at each function and determine its role in the overall algorithm. By doing this and understanding each function, coding the actual implementation didn’t seem as daunting as it first appeared.
#### Closing Thoughts
This project helped me understand RSA on a much deeper level, but even more importantly, it helped me learn key concepts in number theory such as why prime factorization is difficult (in the code breaking section), GCDs (Euler’s Algorithms), modular arithmetic, and much more. However, my biggest take away from this is that even a concept such as RSA that seems so complicated can be easily learned by first looking at the small concepts and building up to the larger ones. By taking my time and reading the book and watching the lectures before starting any code, the process that I once looked at with worry was completed much easier than I had thought. By working through one function at a time, and testing each one to ensure they worked properly before moving on to the next, I was able to avoid major headaches as I wrapped this project up. However, I must point out that my careless mistake mentioned in the beginning of these findings, took out hours of my day. Thus, another important take away is to take your time and double check each line of work, especially when you are confident as this confidence can lead to carelessness and cause major setbacks in your process.


### 7. FME Exploration



* Explain in detail why RSA needs to use an FME function and cannot just simply use the Python Mod function % .

* You may use your arguments from the Number theory Mastery Workbook.

* Simple examples can be used or charts and graphs.


In [38]:
def FakeFME():
    x = pow(b,n) # calculate b^n

    result = x % d # find b^n mod d
    return result

When I looked at FakeFME at first, I saw that it was performing much faster than the FME that is used in the actual implementation for RSA above.

By utilizing the time library in python, I analyzed the runtime of FME with a few different values.

When looking at 7^644 mod 645, FakeFME had a run time of 3.5e-05 seconds while FME had a runtime of 0.0015 seconds. However, I knew that this initial investigation could be deceiving so I continued looking into larger values. 

In the real world, RSA uses extremely large prime numbers I decided to try out 7^6440000000 mod 645 to compare the runtime. When I did this, I saw that the FME function that we use had a runtime of 6.3 seconds whereas the FakeFME function I created never returned a result because it was too slow. While this did make me suspect that we needed to use our FME function due to time complexity, as this didn't give me any results for the FakeFME function I had to keep on looking.

Thus, when I finally changed the value of n to 644000, I once again saw that FME ran for 0.0012 seconds whereas the FakeFME ran for 0.2 seconds. These findings confirmed my suspicions that we need to use an FME function in order to properly find the modulus of large numbers. On the other hand, the built-in mod function cannot adequately handle large numbers. Thus, as RSA is built on the concept of modular arithmetic for both encoding (C = M^e mod n) and decoding (M = C^d mod n) it is essential that we have a fast and reliable way to compute these values. 

## CODE BREAKING ##

This section of the project is only available to students exchanging codes by the Friday (midnight) before the project is due.

After you have tested your RSA package yourself, and tested it with classmates by publishing both the private and public keys on Piazza, post 2 messages with just the public keys for people to break on the "Just Public Keys" thread - use both very small n ‘s (under 1000) for practice, and some with a challenge.


**Implementing a factoring algorithm:**

Begin by coding the basic brute force factorization algorithm given in pseudocode below.

Brute Force Factoring
<pre><code>def factorize(n):
    # n is a number, return the smallest factor of n
    for i from 2 to n-1:
        if i divides n:
            return i
        return FALSE
        </code></pre>


In [39]:
def factorize(n):
    # n is a number, return the smallest factor of n
    for i in range(2,(n-1)): # loop through all numbers from 2 to n-1 untill a factor is found

        if n%i == 0: # if i is a factor of n return i
            return i
        
    return False # if no factor is found return false

### 8. How to Break Code. 
* Explain in detail how breaking works in this text block. 
* What are the complete steps? What tools do you need?
* How secure is RSA? Why is it difficult to break codes in RSA? 
* Is our implementation of RSA secure? What are it's flaws?









As was explained in the intro to this code breaking section, this alrgorithm is a brute force factorization algorithm. This means that this algorithm will keep on running until it comes up with a factor of n. All that was needed to do this was a loop and the modulo operator to see if the value of i was a factor of n or not. By going through every value from 2 to 1 less than n, if a factor existed it could eventually be found. However, if no factor existed this function would just return false.
However, this may cause one to ask how secure RSA is. As metioned in the lectures and the textbook, finding the inverse of the product of two primes can be extremely difficult especailly as the product gets larger and larger. As is shown below, as n grows, our brute force algorithm takes more and more time. However, our implementation of RSA is not that secure as we can use an algorithm such as the basic brute force factorization algorithm above to break our public keys to decrypt encoded messages. Thus, our flaw is that we are using prime numbers that are too small so it is realivlety easy for us to use a brute force method to crack the public keys. However, if we were to use much larger prime numbers, such as is used in acutal RSA, this would no longer be an option for us, as finding the product would be simple but factoring this product of two primes would have a complexity of O(n).

### 9. Decode!  Use a mix of text and code blocks

* Decode one example in detial showing all the steps.
* Decode and Respond to 3 "just codes with public keys" with different sizes of n. Include complete results here.
* What did you notice about larger n s?

Before I was able to decode any messages I saw that I would have to find the other factor and then also the private key to decrypt the message. Thus, instead of having to do this over and over again for all three message I decided to make another function below.

In [40]:
def find_private_key(n, p, e):
    q = n / p #since we know p is one factor we can find q by dviding n by q
    d = Find_Private_Key_d(e, p, q) # use Find_Private_Key_d to find d
    
    return d # return the private key

#### Example 1 - Small Value of N 
Now that we have this we can start decoding messages. This first one was posted by a Professor Stade. In order to do this we first put n through our facotirze function to get the first factor. Then we pass the public key as well as the first factor into our find_private_key function. This then returns our private key value which we can use with our decode function to figure out what they cipher message says. Moreover, as one fo the questions above asked to look at the larger values of n, I read through the python documentation and used the time libarary to see how runtime changed as n got larger. Source: https://docs.python.org/3/library/time.html#time.time

In [41]:
# Public Key: (703, 113)

import time 
start = time.time() # use time libary to track start time

n = 703
e = 113
p = factorize(n) # find the first factor of n

end = time.time() # use time libary to track end time
print("Factorize runtime = " + str(end - start) +"") # print out runtime

d = find_private_key(n, p, e) # find the private key

Cipher = [544, 472, 233, 242, 250, 555, 591, 550, 376, 364, 210, 165, 526, 47, 555, 95, 476, 210, 242, 165, 95, 233, 526, 210, 376, 95, 233, 242, 364, 210, 242, 224, 376, 95, 364, 233, 47, 242, 210, 555, 376, 165, 472, 242, 555, 410, 242, 250, 95, 233, 233, 47, 145]

decoded_cipher = Decode(n, d, Cipher)
print(decoded_cipher)

Factorize runtime = 6.127357482910156e-05
The Conquistador's treasure is buried south of Creed.


Now that we have found this all that is left is to come up with a response and then encrypt it using the orignal public key and my Encode function from earlier inorder to send it back to the orginial sender on Piazza.

In [42]:
# Public Key: (703, 113)

cipher_repsonse = "Where is Creed and what type of treasure is buried there and how much does it cost?"

encoded_cipher_repsonse = Encode(703, 113, cipher_repsonse)
print(encoded_cipher_repsonse)

[368, 472, 233, 95, 233, 242, 364, 210, 242, 250, 95, 233, 233, 47, 242, 526, 591, 47, 242, 541, 472, 526, 165, 242, 165, 581, 519, 233, 242, 555, 410, 242, 165, 95, 233, 526, 210, 376, 95, 233, 242, 364, 210, 242, 224, 376, 95, 364, 233, 47, 242, 165, 472, 233, 95, 233, 242, 526, 591, 47, 242, 472, 555, 541, 242, 523, 376, 511, 472, 242, 47, 555, 233, 210, 242, 364, 165, 242, 511, 555, 210, 165, 195]


#### Example 2 - Medium Value of N 

In [43]:
#Public Key (n, e) = (870473, 14513)

import time 
start = time.time() # use time libary to track start time

n = 870473
e = 14513
p = factorize(n) # find the first factor of n

end = time.time() # use time libary to track end time
print("Factorize runtime = " + str(end - start) +"") # print out runtime

d = find_private_key(n, p, e) # find the private key

cipher_message = [787825, 226245, 452721, 869061, 485679, 779636, 287189, 452721, 869061, 226245, 869061, 145789, 287189, 420006, 420006, 287189, 810665, 610577, 466742, 485679, 869061, 810665, 779636, 226245, 466742, 466742, 244428, 508074, 405134, 244428, 869061, 420006, 227577, 852539, 869061, 452721, 227577, 723754, 244428, 633537]

decoded_message = Decode(n, d, cipher_message)
print(decoded_message)

Factorize runtime = 9.894371032714844e-05
Was this a difficult challenge for some?


In [44]:
#Public Key (n, e) = (870473, 14513)

diffiulty_response = "Thanks to the factorize algorithm, breaking this didn't prove to be too difficult."

encoded_diffiulty_response = Encode(870473, 14513, diffiulty_response)
print(encoded_diffiulty_response)

[60140, 779636, 226245, 508074, 324214, 452721, 869061, 485679, 227577, 869061, 485679, 779636, 244428, 869061, 420006, 226245, 810665, 485679, 227577, 852539, 287189, 173050, 244428, 869061, 226245, 466742, 405134, 227577, 852539, 287189, 485679, 779636, 723754, 102594, 869061, 840378, 852539, 244428, 226245, 324214, 287189, 508074, 405134, 869061, 485679, 779636, 287189, 452721, 869061, 145789, 287189, 145789, 508074, 585157, 485679, 869061, 82078, 852539, 227577, 345612, 244428, 869061, 485679, 227577, 869061, 840378, 244428, 869061, 485679, 227577, 227577, 869061, 145789, 287189, 420006, 420006, 287189, 810665, 610577, 466742, 485679, 557446]


#### Example 3 - Large Value of N 

In [45]:
#Public Key(n, e) = (1629592673, 13)

import time 
start = time.time() # use time libary to track start time

n = 1629592673
e = 13
p = factorize(n) # find the first factor of n

end = time.time()  # find the first factor of n
print("Factorize runtime = " + str(end - start) +"") # print out runtime

d = find_private_key(n, p, e) # find the private key

final_cipher = [336489089, 790495352, 1026156174, 792037268, 328094142, 905762081, 1209896438, 1113193909, 1144895309, 1277232906, 1259837692, 790495352, 1113193909, 792037268, 328094142, 1217356319, 1113193909, 1144895309, 328094142, 1034684646, 1294431967, 1420736799, 1084640708]

decoded_question = Decode(n, d, final_cipher)
print(decoded_question)

Factorize runtime = 0.00302886962890625
Best Condiment and why?


In [46]:
#Public Key(n, e) = (1629592673, 13)

condiment_response = "Hot sauce as it adds a kick to anything you put it on."

encoded_condiment_response = Encode(1629592673, 13, condiment_response)
print(encoded_condiment_response)

[1028400221, 1209896438, 792037268, 328094142, 1026156174, 1217356319, 646001319, 904585720, 790495352, 328094142, 1217356319, 1026156174, 328094142, 1277232906, 792037268, 328094142, 1217356319, 1144895309, 1144895309, 1026156174, 328094142, 1217356319, 328094142, 1400752826, 1277232906, 904585720, 1400752826, 328094142, 792037268, 1209896438, 328094142, 1217356319, 1113193909, 1420736799, 792037268, 1294431967, 1277232906, 1113193909, 981351809, 328094142, 1420736799, 1209896438, 646001319, 328094142, 1234157864, 646001319, 792037268, 328094142, 1277232906, 792037268, 328094142, 1209896438, 1113193909, 1551412891]


After initailly breaking and responding to these three messages I was unable to see much of a difference bettwen the values of n. Thus, I decided to track the time of the factorize function and noticed that there was a huge diffrence in speed as the digits of n grew. The first trial was a 3 digit value and took about 0.0001 seconds. Next when n had a 6 digit value, it took about 0.0002 seconds. Finally, when n was a 10 digit value the time went to 0.005 seconds. This shows that as n grows, it becomes harder and harder to find its prime factorization, as was suspected above with the FME and fakeFME functions.


### 10. Custom CODE Feature ##
The last 15 points of the require a custom feature in your project. This is an opportinity for you to explore an RSA or coding topic of interest to you. At this point it is not about points, but exploring advanced ideas relevant to you.  This is also a feature that should be relevant to your programming ability. If you are in 1300, creating a main type function may be enough. If you are an experienced programmer, find a topic to push yourself. 

* The custom feature should be a "Stand Alone" feature at the end of the notebook.
* If you want to use code from above, please copy the functions again as part of your feature so it can be tested independently.
* Be sure to provide a demo of your feature showing that it works. This is a good check for you, shows us it works, and helps us if we are unable to get your feature to work when grading.
* Do not forget the self-grading element.

Custom Features could one or more of the following:

1. Code breaking improvements. An exploration of factoring improvements and analyze how effective they are. Must include some kind of timing analysis and multiple code breaking. A superficial treatment will not recieve full points. Must be throughly tested with excellent investigations to recieve full points.
2. A Python "main" function that allows a user to "Get keys/Encode/Decode/Break Codes" etc... This can use elements of initial RSA code above HOWEVER - Please copy and pan should be organized below. *Please include your complete new implementation below.*
3. A script to read codes from Piazza data. You can copy and paste codes from Piazza into a txt files and then have your script read it. This is a VERY helpful tool for doing the project as well. 
4. Exploration of advanced factoring alogrithms (see Moodle) Try Pollard's Rho <- super satisfying. (full points if well - impemented with thoughtful examples). 
5. Advanced complexity analysis. 
6. Frequency anaylsis from our Piazza post.
7. A deep dive in the mathematics of the RSA proofs.
8. Advance code breaking challenges with  - this should be anorganized and well documented effort.
9. More options available, all include a coding element. Please ask is you have an unique idea. 

The Custom Feature is an important part of the project, and it should be a non-trivial response. 
Please help organize your Custom Feature by breaking it up into sections - ie. not one long block of text.
Mininimally executed, "dialling it in" type features will not recieve full points. 
See below for more detials on grading of this section.



 




In [65]:
import time 

def menu(): # Print out a menu with all the options that a user can pick
    print("")
    print("------Welcome to RSA------")
    print("Select an option below:")
    print("1. Get public and private keys")
    print("2. Encode Message")
    print("3. Decode Message")
    print("4. Break Code Using Basic Brute Force Factorization")
    print("5. Quit")

def get_public_private_key(): 
    print("Please enter two prime numbers.") 
    p = int(input("Enter your first prime numner:")) # ask user to enter the first prime number
    q = int(input("Enter your second prime numner:")) # ask user to enter the second prime number
    n, e = Find_Public_Key_e(p, q) # find the public key
    d = Find_Private_Key_d(e, p, q) # find the private key
    return n, e, d # return everything to the main function

def encode_message(n, e):
    message = input("What is the message you would like to encrypt:") # ask user for a message
    encoded_msg = Encode(n, e, message) # use the Encode function to encrypt the message
    print(encoded_msg) #return the encoded message

def decode_message(n, d):
    encoded_numbers = input("What is the message you would like to decrypt (EXCLUDE []):") # take in an encoded message   
    encoded_str_list = encoded_numbers.split (", ") #spilt the encoded message up at at each comma and instert it into a lsit
    
    encoded_msg = []
    for i in encoded_str_list: # convert the list from a list of strings to a list of ints
        encoded_msg.append(int(i))

    decoded_msg = Decode(n, d, encoded_msg) # use the Decode function to decrypt the message
    print(decoded_msg) #return the original message

def brute_force(n, e):
    start = time.time() # use time libary to track start time

    p = factorize(n) # find the first factor of n

    end = time.time()  # find the first factor of n
    print("Factorize runtime = " + str(end - start) +"") # print out runtime

    d = find_private_key(n, p, e) # find the private key
    
    return d # return the value for d

def main():
    choice = 0 # declare a variable choice that is set
    # declare variables to hold values needed for endcoding and decoding
    n = 0
    e = 0
    d = 0
    
    while choice != 5: # don't exit untill the user chooses to quit
        menu() # display the menu
        choice = int(input("What would you like to do")) # ask user to enter their choice
        
        if choice == 1: # if the user chooses this choice call get_public_private_key and then print out both key pairs
            n, e, d = get_public_private_key()
            print("Your public key pair is (" + str(n) + "," + str(e) + "). This will be used to encrypt messages.")
            print("Your private key pair is (" + str(n) + "," + str(d) + "). This will be used to decrypt messages.")
            
        elif choice == 2:  # if the user chooses this choice call encode_message and then print out encoded message
            print("Enter your public key pair")
            n = int(input("What is your value for n:"))
            e = int(input("What is your value for e:"))
            encode_message(n, e)
            
        elif choice == 3: # if the user chooses this choice call decode_message and then print out decoded message
            print("Enter your private key pair")
            n = int(input("What is your value for n:"))
            d = int(input("What is your value for d:"))
            decode_message(n, d)
            
        elif choice == 4:  # if the user chooses this choice call find_private_key to break the RSA encryption
            print("Enter your public key pair")
            n = int(input("What is your value for n:"))
            e = int(input("What is your value for e:"))
            d = brute_force(n, e)
            print("Your private key pair is (" + str(n) + "," + str(d) + "). This will be used to decrypt messages.")

        elif choice == 5: #exit
            break
            
        else: #check for invalid choice
            print("Invald choice, please try again")
            
    print("Goodbye!") #print exiting message
    
if __name__ == '__main__':
    main()


------Welcome to RSA------
Select an option below:
1. Get public and private keys
2. Encode Message
3. Decode Message
4. Break Code Using Basic Brute Force Factorization
5. Quit


What would you like to do 6


Invald choice, please try again

------Welcome to RSA------
Select an option below:
1. Get public and private keys
2. Encode Message
3. Decode Message
4. Break Code Using Basic Brute Force Factorization
5. Quit


What would you like to do 5


Goodbye!


## Self grading of custom feature ##

Here in this block

Please rate what score out of 15 your custom feature merits given the criteria above:

* For example, if you are brand new to programming, using a main function could be an amazing feature - tell me how this helped you move to a new level.
* In what ways did YOU push yourself? Did you try something you've never done before?
* Alternatively, if you just did not have the time to do the custum feature, that is actually just fine and a reasonable choice for an adult. No judgment.

I would grade this a 11 out of 15. While I am not brand new to programing, I only have a year of experience as next semester will be the start of my sophomore year of college. Thus, so far I have only worked with C++ and while the majority of the concepts are the same, learning the syntax and working through those errors took me a long time. By doing this main function I was able to solidify a lot of those skills and also simplify my testing in the process. While this use of python was new to me, I have used menus in C++ so the main ideas did not change. Thus, while I did work through the process of learning a new language, as many of the ideas were the same it was more a matter of time to figure out syntax and watch python videos, not actually learn the concepts. However, even after this process I am a bit unclear about why the following code block is necessary.

In [26]:
if __name__ == '__main__':
    main()

------Welcome to RSA------
Select an option below:
1. Get public and private keys
2. Encode Message
3. Decode Message
4. Break Code Using Basic Brute Force Factorization
5. Break Code Using Pollard's Rho
6. Quit


What would you like to do 6


Goodbye!


To my understanding this just calls main, but I was unable to figure out why we cannot do so without the if clause. Other than that the proccess of writing this main function just took me a lot of time as I had to work through these syntax errors, but as I had been doing this the entire project, by the time I got around to this function I had already started to get the hang of the basics. Another problem I had to work with was inputs, as I didn't know how to declare types and even when I figured that out I had a lot of issuses with inputting the encoded message as a list of integers.